---
title: "Assignment 1"
---

# Assignment 1

```{r}
options(repos = c(CRAN = "https://cran.rstudio.com/"))
install.packages("rmarkdown")
install.packages("knitr")
install.packages("dslabs")
library(dslabs)

data("polls_us_election_2016")
head(polls_us_election_2016, 10)

sum(is.na(polls_us_election_2016))

polls_us_election_2016_new <- polls_us_election_2016  # We gave new name to the dataset

polls_us_election_2016_new[] <- lapply(polls_us_election_2016_new, function(x) {
    if (is.numeric(x)) {
        x[is.na(x)] <- 2001  # Now we are changing some NA values with my birth year
    } else {
        x <- as.character(x)
        x[is.na(x)] <- "Tuba"  # Lastly changing some NA values with my name
    }
    return(x)
})

head(polls_us_election_2016_new,10)
sum(is.na(polls_us_election_2016_new))
```

My first assignment has two parts.

## (a)

I selected the third talk with Baykal Hafızoğlu.

Firstly, Mr. Baykal did his master's degree in METU and doctor degree in America. And he pursued his career in US. He has a wide knowledge of different markets. Right now he is working at FICO company as a director of platform management. I actually admired his passion to complete all the education levels successfully. Apart from, that whole speech was very informative. Now I would like to summarize the speech with what I have learned. Actually, our industrial engineering courses are quite enough to be data scientist. For example, data mining was covering descriptive analysis, regression class was covering diagnostic analysis, simulation class was covering predictive analysis and lastly our optimization and heuristic class was covering prescriptive analysis. In industrial engineering department we are grown up with that background, I didn't know this. Another thing that is mentioned in the video was to have a very well-defined problem is very crucial for deploying our models and starting to a new project. To improve our pieces of software, actively listening to the end user is very important. They are right most times. So we need to adjust our software according to the end user. And data science may seem like you need to do hard programming, but this is a misleading concept because most of the time you deal with other dirty jobs like talking to the customer about the problem, trying to get data, cleaning the data, adjusting the data etc. When finalizing our project, we shouldn't forget to refer to the problem definition. And we need to show our work with KPI's, other performance parameters. In conclusion, he recommends us to know what we want to do in this sector, after that we can adjust our work area.

"Which of the following is the type of dance Baykal Hafızoğlu's danced? A) Bachata B) Tango C) Salsa D) Freestyle"

"Answer is Tango"

"How many data analytics method exists?"

"Answer: -Descriptive Analytics -Diagnostic Analytics -Predictive Analytics -Prescriptive Analytics"

## (b)

install.packages("dslabls")

```         
library(dslabs) 
data("polls_us_election_2016") 
head(polls_us_election_2016,10)
sum(is.na(polls_us_election_2016))
polls_us_election_2016_new <- polls_us_election_2016 #We gave new name to the dataset

polls_us_election_2016_new[] <- lapply(polls_us_election_2016_new, function(x) {
     if (is.numeric(x)) {
         x[is.na(x)] <- 2001  #Now we are changing some na values with my birth year
     } else {
         x <- as.character(x)
         x[is.na(x)] <- "Tuba"  #Lastly changing some na values with my name
     }
     return(x)
 })
head(polls_us_election_2016_new,10)
sum(is.na(polls_us_election_2016_new))
```
